version: "3.9"

services:
  youtube-clone-frontend-dev:
      container_name: youtube-clone-frontend-dev
      build:
        context: ./
        dockerfile: Dockerfile.dev
      volumes:
        - .:/app
        - "/app/node_modules"
      ports:
        - "3002:3000"

  youtube-clone-frontend-test:
    container_name: youtube-clone-frontend-test
    image: my-awesome-app-jbp-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - "/app/node_modules"
    command: ["npm", "run", "test"]
