FROM node:latest

WORKDIR /usr/src/app

ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm install
# RUN npm i react-scripts@5 -g

COPY ./ ./

# ENV APP_PORT 8080

EXPOSE 3000

CMD ["npm", "start"]